services:
  forgejo:
    image: "codeberg.org/forgejo/forgejo:13.0.3"
    container_name: forgejo
    restart: always
    expose:
      - "3000"
    environment:
      - TZ=UTC
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__DISABLE_SSH=true
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__openid__ENABLE_OPENID_SIGNIN=false
      - FORGEJO__mailer__ENABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
      - "traefik.http.routers.forgejo.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.http.routers.forgejo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.forgejo.middlewares=basic-security"
    volumes:
      - ./data/forgejo:/data

networks:
  default:
    name: intranet
    external: true
