# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json

services:
  forgejo:
    image: "codeberg.org/forgejo/forgejo:13.0.3"
    container_name: forgejo
    restart: unless-stopped
    networks:
      - gateway-forgejo-resource
    expose:
      - "3000"
    environment:
      - TZ=UTC
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__DISABLE_SSH=true
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__openid__ENABLE_OPENID_SIGNIN=false
      - FORGEJO__mailer__ENABLED=true
    volumes:
      - ./data/forgejo:/data

networks:
  gateway-forgejo-resource:
    name: gateway-forgejo-resource
    external: true
