[providers]
keepass = { type = "keepass", database = "../../selfhost.kdbx" }

[secrets]
FORGEJO_cors_ALLOW_DOMAIN = { value = "production/forgejo/FORGEJO_cors_ALLOW_DOMAIN", provider = "keepass" } # https://example.com
FORGEJO__server__DOMAIN = { value = "production/forgejo/FORGEJO__server__DOMAIN", provider = "keepass" } # example.com
FORGEJO__server__ROOT_URL = { value = "production/forgejo/FORGEJO__server__ROOT_URL", provider = "keepass" } # https://example.com
FORGEJO__mailer__FROM = { value = "production/forgejo/FORGEJO__mailer__FROM",  provider = "keepass" } # Forgejo <forgejo@example.com>
FORGEJO__mailer__PROTOCOL = { value = "production/forgejo/FORGEJO__mailer__PROTOCOL", provider = "keepass" } # smtp+starttls
FORGEJO__mailer__SMTP_ADDR = { value = "production/forgejo/FORGEJO__mailer__SMTP_ADDR", provider = "keepass" } # smtp.example.com
FORGEJO__mailer__SMTP_PORT = { value = "production/forgejo/FORGEJO__mailer__SMTP_PORT", provider = "keepass" } # 587
FORGEJO__mailer__USER = { value = "production/forgejo/FORGEJO__mailer__USER", provider = "keepass" } # forgejo@example.com
FORGEJO__mailer__PASSWD = { value = "production/forgejo/FORGEJO__mailer__PASSWD", provider = "keepass" } # password
